### ISSUE TITLE
[Gallery][All Platforms]Infobadge- The Header 'Material', 'Fluent' or 'Cupertino' is not specified.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#1007]
### Current behavior

![Infobadge name issue](https://github.com/unoplatform/uno/assets/74563602/6f47098e-8014-4d62-8ede-a7d4519e33c7)

### Expected behavior

Infobadge page is belong to 'Material' or 'Fluent' or 'Cupertino' should be present.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Infobadge" from the "UI Component" list.
4. Notice that for Infobadge page, this is belongs to which one of them  'Material' or 'Fluent' or 'Cupertino' is missing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by kazo0** [comment]
@agneszitte this one can be closed, it is the desired behavior since it is a design agnostic sample

**Comment by agneszitte** [comment]
I think we should have a fluent tab (maybe material also?) like the other controls

**Comment by sakshi173** [comment]
Verified I am closing it.
