### ISSUE TITLE
[ios/droid] lock the app in Portrait mode on mobile.

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Gallery#102]
## What would you like to be added:
lock the app in Portrait mode on mobile.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by Xiaoy312** [comment]
do we still need to lock portrait mode if unoplatform/uno#5095 is no longer an issue?
if so, do we apply to all mobile device or phone (leaving tablets intact) only?

**Comment by francoistanguay** [comment]
Fair, we can keep Landscape enabled for now but if we find more landscape issues, I dont see a point of supporting portrait on Gallery.
