### ISSUE TITLE
[Gallery][WASM] AutoSuggestBox-There is no space on the left side of the control's name text in the suggestion list.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#1069]
### Current behavior

![Autossuggest issue](https://github.com/unoplatform/uno/assets/74563602/6b178cdc-9647-4e03-b80c-17e6568455e0)

### Expected behavior

![Autossuggest correct](https://github.com/unoplatform/uno/assets/74563602/9ca4464c-28df-4f52-a91a-24fab8feb915)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap "Autosuggest Box" from the "UI Components" list.
3. Type any letter in the 'searchbox'
4. Make sure combo box list opens with all the controls name.
5. Notice that There is no space on the left side of the control's name text in the suggestion list.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by morning4coffe-dev** [comment]
Same issue as https://github.com/unoplatform/Uno.Gallery/issues/1122 (posted more details there)

**Comment by jhanvi03** [comment]
When we have few suggestion like 1 or 2, there is huge gap between the suggestion box and the text box on all the platforms
![Screenshot 2024-07-03 at 12 06 54 PM](https://github.com/unoplatform/Uno.Gallery/assets/173818531/b82a4634-5b9f-4194-8e43-01d14d65ebfd)

**Comment by morning4coffe-dev** [comment]
@jhanvi03 Thanks for testing this out. I am seeing very different behavior on WASM now: 
![image](https://github.com/unoplatform/Uno.Gallery/assets/78549750/162d3ab0-cc4c-46d7-a177-a1ca9e3db301)
What browser are you using? What is your display scaling?

**Comment by jhanvi03** [comment]
@morning4coffe-dev For Windows I tested on Edge and for Mac- Chrome

**Comment by jhanvi03** [comment]
After performing a search, the table remains fixed in its original position when scrolling the page.

https://github.com/unoplatform/Uno.Gallery/assets/173818531/f41d1c81-f31c-4357-acb6-42ae75ef5000

**Comment by Xiaoy312** [comment]
the base issue submitted by @sakshi173 is a
problem of same nature as: #1093

**Comment by Xiaoy312** [comment]
@jhanvi03 
https://github.com/unoplatform/Uno.Gallery/issues/1069#issuecomment-2206758907 && https://github.com/unoplatform/Uno.Gallery/issues/1069#issuecomment-2211338369
the issue you encountered where the flyout content remains stationary and detaches from its host on scrolled
is a separate issue, please open a new issue for that if there isn't already one.

**Comment by morning4coffe-dev** [comment]
> the base issue submitted by @sakshi173 is a problem of same nature as: #1093

Ah, I thought so too. I will take a look into it, thanks @Xiaoy312

**Comment by agneszitte** [comment]
> @jhanvi03 [#1069 (comment)](https://github.com/unoplatform/Uno.Gallery/issues/1069#issuecomment-2206758907) && [#1069 (comment)](https://github.com/unoplatform/Uno.Gallery/issues/1069#issuecomment-2211338369) the issue you encountered where the flyout content remains stationary and detaches from its host on scrolled is a separate issue, please open a new issue for that if there isn't already one.

Tracking related issue for this: https://github.com/unoplatform/Uno.Gallery/issues/1130

**Comment by agneszitte** [comment]
Related issue: https://github.com/unoplatform/uno/issues/15967#issuecomment-2394712627

**Comment by morning4coffe-dev** [comment]
This issue should be fixed now via https://github.com/unoplatform/Uno.Gallery/pull/1173.

**Comment by jhanvi03** [comment]
Tested WASm on windows and mac, Space does appear on left side of the control.
Versions:
Package	Referenced version	Updated version
Uno.CommunityToolkit.WinUI.UI.Controls	[7.1.200](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/7.1.200)	[7.1.203](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/7.1.203)
Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid	[7.1.200](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid/7.1.200)	[7.1.203](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid/7.1.203)
Uno.Core.Extensions.Compatibility	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Compatibility/4.0.1)	[4.1.1](https://www.nuget.org/packages/Uno.Core.Extensions.Compatibility/4.1.1)
Uno.Core.Extensions.Disposables	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.1)	[4.1.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.1.1)
Uno.Sdk	[5.3.96](https://www.nuget.org/packages/Uno.Sdk/5.3.96)	[5.6.0-dev.53](https://www.nuget.org/packages/Uno.Sdk/5.6.0-dev.53)
Package | Referenced version | Updated version
-- | -- | --
Uno.CommunityToolkit.WinUI.UI.Controls | 7.1.200 | 7.1.203
Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid | 7.1.200 | 7.1.203
Uno.Core.Extensions.Compatibility | 4.0.1 | 4.1.1
Uno.Core.Extensions.Disposables | 4.0.1 | 4.1.1
Uno.Sdk | 5.3.96 | 5.6.0-dev.53

![Image](https://github.com/user-attachments/assets/c15192c4-3711-4edb-a9a8-bf38aa086b83)
![Image](https://github.com/user-attachments/assets/4a9396c6-3812-4a35-81b5-58636dc6a0ed)
![Image](https://github.com/user-attachments/assets/1f6a9b82-f9eb-4ae9-b3f7-09e13fcae0b3)
