### ISSUE TITLE
[any-plat][NavView] deselecting item by selecting another leave the former in "Selected" state

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Gallery#107]
## Current behavior

Deselecting item by selecting another leave the former in "Selected" state:
![20210204 mux-navview deselect](https://user-images.githubusercontent.com/2359550/106919216-ede2d600-66d7-11eb-91b5-841658795d8a.gif)

## Expected behavior

The deselected item should go back to "Normal" or "Checked" state

## How to reproduce it (as minimally and precisely as possible)
Checkout `master`
Comment out `App.AddNavigationItems.NavViewItemVisualStateFix` method
Launch the app on any platform
Click on different navigation items

## Environment

Nuget Package: Uno.UI
Package Version(s): 3.5.0-dev.256
Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins: n/a

## Anything else we need to know?
Current workaround is to force reset the visual state when `IsSelected` becomes false.

**Comment by MartinZikmund** [comment]
@jeromelaban So far I am unable to figure this one out, especially as it even happens on UWP too. Weirdly enough, using similar styles in a blank app I cannot reproduce it. Luckily the workaround works, so it is not a blocker.

**Comment by Xiaoy312** [comment]
The reason why the default style works, is that there is no distinction between selected vs normal state other than the "SelectionIndicator" that is managed by the NavView (the parent, not NVItem).

**Comment by Xiaoy312** [comment]
The reason why the default style works, is that there is no distinction between selected vs normal state other than the "SelectionIndicator" that is managed by the NavView (the parent, not NVItem).
---
It seems that microsoft has fixed this issue in 2.5.0, but it WAS present in 2.4.3:
<details>
 <summary>20210217 nvi selected 2.4.3.gif</summary>

![20210217 nvi selected 2 4 3](https://user-images.githubusercontent.com/2359550/108236277-b7b04800-7114-11eb-9ecb-7c28fe7dd3f1.gif)
^ notice that the previous item state never resets back to "Normal"
</details>

<details>
 <summary>20210217 nvi selected 2.5.0.gif</summary>

![20210217 nvi selected 2 5 0](https://user-images.githubusercontent.com/2359550/108236169-97808900-7114-11eb-9814-6bba7ae86e20.gif)
</details>

Here is the PR containing the fix: microsoft/microsoft-ui-xaml#2625

I would assume we need to port that into uno as well.

**Comment by Xiaoy312** [comment]
@MartinZikmund ^

**Comment by MartinZikmund** [comment]
@Xiaoy312  that is curious as I ported NavView based on the current version around December 2020, so these changes should already be included. Can you please compare the relevant changes with our code to see if I didn't miss something somewhere? Or maybe some part of the style is different?

**Comment by Xiaoy312** [comment]
<details>
    <summary>note</summary>

    issue can no longer reproduced on current master even after commenting out the body of `NavViewItemVisualStateFix`
        - ios: OK iPad Pro (9.7in) iOS 14.4
        - wasm: OK
        - win: OK

    checking out a version when the issue is posted
        f0803a77 2021-02-04 Merge pull request #101 from unoplatform/dev/xygu/20210128/muxc-nav-view
        ^ after commenting out the body of `NavViewItemVisualStateFix`
            > still cant repro on uno..?
            - win: FAIL
            - ios: OK iPad Pro (9.7in) iOS 14.4
            - wasm: OK
            - android: OK Tablet M-DPI 10.1in Q 10.0
        ^ the visual state on `MUX_NavigationViewItemPresenterStyleWhenOnLeftPane` appears to be okay for uno
        ^ package version 3.5.0-dev.256 matches the one in the issue

    same issue cant be reproduced with the attached sample either on android or wasm; it is only on uwp that it fails
        > previous item resets back to `Normal` state from `Selected` (this is the expected behavior)
        ^ note: the `Loaded` handler needs to be moved into a Button.Click, as Loaded seems to be too early, on non-uwp platforms
</details>

Cant seem to reproduce the issue anymore, despite going back to the older commit.
