### ISSUE TITLE
[Wasm] DataGrid doesn't load

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/Uno.Gallery#1091]
## Current behavior

When I open the Gallery on Edge latest, the DataGrid doesn't seem to load anymore even after a few minutes. 
![image](https://github.com/unoplatform/Uno.Gallery/assets/78549750/48b43916-c396-4ce4-8f5f-6c519edcfc39)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
@Darsh0307 could you launch the app in debug and see if there are any exceptions showing up for this particular sample? Thanks!

**Comment by Darsh0307** [comment]
@jeromelaban  @morning4coffe-dev  , Its loading for me 

<img width="1182" alt="Screenshot 2024-02-13 at 9 27 04 AM" src="https://github.com/unoplatform/Uno.Gallery/assets/90713481/7550aa0a-ae45-41f0-b592-fdc82b0be05d">

**Comment by Darsh0307** [comment]
cc @MartinZikmund  @morning4coffe-dev 
<img width="539" alt="Screenshot 2024-02-13 at 11 43 57 AM" src="https://github.com/unoplatform/Uno.Gallery/assets/90713481/0cc582d0-70f8-48bf-9bb3-1874a0811ad7">
<img width="531" alt="Screenshot 2024-02-13 at 11 43 48 AM" src="https://github.com/unoplatform/Uno.Gallery/assets/90713481/d89ab20a-073b-4c99-8f61-96e0e69344e3">

**Comment by Youssef1313** [comment]
It looks like this is already fixed. It works fine on staging https://unogallerycanary.z27.web.core.windows.net/
