### ISSUE TITLE
Flyout samples are all Material

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#1094]
## Current behavior

Even in Fluent the samples are actually Material design for Flyout

![image](https://github.com/unoplatform/Uno.Gallery/assets/1075116/e66f89cc-d7e7-47f8-9f61-58ee6cc8f7a3)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by morning4coffe-dev** [comment]
Similar to https://github.com/unoplatform/Uno.Gallery/issues/1093

**Comment by kazo0** [comment]
Yeah there's no real good way around this :/ the resources for the flyouts seemingly only search at a the top app level

**Comment by kazo0** [comment]
We could use a custom style for each of the Flyouts that injects the `XamlControlsResources` as part of the style
