### ISSUE TITLE
Selecting an item scrolls the navigation view up

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#1096]
## Current behavior

![scrolluo](https://github.com/unoplatform/Uno.Gallery/assets/1075116/5a551219-4e51-454c-9855-ce071fbee1c4)

## Expected behavior

Should not happen

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
@ramezgerges look familiar? :D

**Comment by kazo0** [comment]
@MartinZikmund is this wasm only?

**Comment by MartinZikmund** [comment]
We did observe it on WASM and it does not happen on iOS in prod version, but we didn't test the rest yet

**Comment by ramezgerges** [comment]
https://github.com/unoplatform/uno/pull/15354 is not merged yet.

**Comment by MartinZikmund** [comment]
@ramezgerges can this be closed now that the linked PR was merged?

**Comment by ramezgerges** [comment]
I think so. If it's working after the fix then yes.

**Comment by MartinZikmund** [comment]
I can confirm this works correctly now 🚀 !
