### ISSUE TITLE
[Gallery][WASM][Home Page] Typo in 'Resources' dropdown

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Gallery#1132]
### Current behavior

The naming convention is not followed for 'Workshop - Tube player' and there is a typo with missing 'n' in 'Uno Playgroud' in both dark and light mode.
<img width="232" alt="Screenshot 2024-07-04 at 12 15 32 PM" src="https://github.com/unoplatform/uno/assets/173818531/a4ba28a3-40e9-4c5a-a6cb-c17c37d5705d">

### Expected behavior

'Workshop - Tube player' should be written as 'Workshop - Tube Player' with capital 'P' 
'Uno Playgroud' should be 'Uno Playground' with 'n' before d

### How to reproduce it (as minimally and precisely as possible)

Steps to reproduce:
1) Open Uno WASM
2) from the navigation bar Click on 'RESOURCES' dropdown
3) Check the 2nd and 5th option

### Works on UWP/WinUI

None

**Comment by Xiaoy312** [comment]
not sure about the "Tube [pP]layer" part, since it is exactly how https://platform.uno/ is doing:
![image](https://github.com/unoplatform/Uno.Gallery/assets/2359550/2d961d35-d9fc-47bd-97cf-889007451ac3)
