### ISSUE TITLE
[web] Navigation dropdowns misbehave upon expanding multiple times

### ISSUE THREAD

**Issue by filiptronicek** [unoplatform/Uno.Gallery#1136]
## Current behavior

The dropdowns on the homepage at https://gallery.platform.uno/ only seem to properly visually isolate themselves once. After that, their backgrounds become transparent.

![gifski-high](https://github.com/user-attachments/assets/8ab6bcf3-14eb-4187-8f77-0342ea3df823)

Canary:

![image](https://github.com/user-attachments/assets/20f885fd-99c0-4e0b-a028-456382fc84f3)

## Expected behavior

Dropdowns maintain visual consistency even after interaction.

## How to reproduce it (as minimally and precisely as possible)

Visit https://gallery.platform.uno/ and click on any of the dropdowns in the top navigation bar.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

There is a big chance this is filed under the wrong repo, in which case, sorry!

**Comment by morning4coffe-dev** [comment]
I think I might have already seen an issue open for this somewhere, but can't find it at the moment. CC @Xiaoy312

**Comment by morning4coffe-dev** [comment]
Thank you for reporting this, @filiptronicek. I think I might have already seen an issue open for this somewhere, but can't find it at the moment. CC @Xiaoy312, you might have more info

**Comment by Xiaoy312** [comment]
We already have an issue tracking this: unoplatform/uno#17366
So I will close this as duplicate.
