### ISSUE TITLE
Wasm UI Tests are not running

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Gallery#1154]
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=134609&view=logs&j=3f30db68-9271-53df-acd9-cedf73364d52&t=0f2f9c6c-9f97-5ad6-0da1-9ef6f814402c&l=832

**Comment by Youssef1313** [comment]
Attempted to fix in https://github.com/unoplatform/Uno.Gallery/pull/1158

But tests are timing out for some reason

**Comment by kazo0** [comment]
@Youssef1313 it looks like the wasm app is getting stuck at the splashscreen. All the screenshots look like this:

![WhenCupertinoClick_04_DisabledChecked_teardown.png](https://github.com/user-attachments/assets/c7a911e6-19c4-4f36-9563-e3d0b14e4966)

**Comment by Youssef1313** [comment]
@kazo0 Interesting

The app was running locally for me with the latest changes, it may be Release-specific issue. I'll continue looking on Monday
