### ISSUE TITLE
[Gallery Canary][iOS][UI Components - InfoBadge] App crashes upon moving cursor on the 'Opacity bar'

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Gallery#1166]
## Current behavior

On iOS device, when the user moves the opacity bar the app crashes.
iOS gallery version: 1.6.0(2409061451.1778)
https://github.com/user-attachments/assets/7450f6cf-faa0-442e-a97b-26c4199ba881

## Expected behavior

App Should not crash

## How to reproduce it (as minimally and precisely as possible)

1. Download, install and open Gallery canary from TestFlight on iOS device.
2. Navigate to Menu -> UI Components -> InfoBadge.
3. Move the opacity bar once or twice.
4. Observe the app crash.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
This is probably the same issue as https://github.com/unoplatform/uno/issues/17656#issuecomment-2338559983

**Comment by kazo0** [comment]
This should be "fixed" by https://github.com/unoplatform/uno/pull/18277

@jhanvi03 Can you retest this, when the Gallery Canaries are working again, of course :)

**Comment by jhanvi03** [comment]
Issue seems to be resolved. Verified with Canary version 1.6.0(2410090204.1809)
