### ISSUE TITLE
[macOS] [Menu] Menu items stuck on Hover state when scrolling

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#117]
## Current behavior

![macosScroll](https://user-images.githubusercontent.com/4793020/107043597-3ca07680-6791-11eb-8c16-0027441310da.gif)

## Expected behavior

Nav items should not stay highlighted after the cursor is no longer on top of them

## How to reproduce it (as minimally and precisely as possible)

Put your cursor on the Nav menu and start to scroll with the mouse scroll wheel.
Note that as items pass under your cursor, their Hover state is activated and never deactivated

## Environment

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )
- [x] Rider

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Duplicate of #118

**Comment by sakshi173** [comment]
As per the above comment, this is duplicate issue and due to that closing it.
