### ISSUE TITLE
Unable to build iOS locally

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#1170]
Unless I remove the references to the Window Community Toolkit, I get these errors when building on macOS with an M2

> Error MSB4018 : The "UnpackLibraryResources" task failed unexpectedly.
> System.ArgumentException: Value does not fall within the expected range. (Parameter 'resourceName')
>    at System.Reflection.TypeLoading.Ecma.EcmaAssembly.GetManifestResourceInfo(String resourceName)
>    at Xamarin.MacDev.Tasks.UnpackLibraryResources.GetAssemblyManifestResources(String fileName)+MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs:line 254
>    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>    at Xamarin.MacDev.Tasks.UnpackLibraryResources.ExtractContentAssembly(String assembly, String intermediatePath)+MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs:line 124
>    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>    at Xamarin.MacDev.Tasks.UnpackLibraryResources.ExecuteImpl() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs:line 90
>    at Xamarin.MacDev.Tasks.UnpackLibraryResources.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs:line 57
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

**Comment by jeromelaban** [comment]
Fix in net9, latest datagrid.
