### ISSUE TITLE
[Material] Disabled `TextBox` with Header PlaceholderText is not legible

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/Uno.Gallery#1176]
## Current behavior

Disabled `TextBox`es with Header and PlaceholderText in Material are not legible:

![image](https://github.com/user-attachments/assets/a0a1e30d-da62-46c3-bf62-02a740762359)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

**Comment by Xiaoy312** [comment]
this is fixed in unoplatform/Uno.Themes#1499

gallery canary is looking good now:
![image](https://github.com/user-attachments/assets/6f8eeb99-2414-407b-8a75-aa954eab1321)
