### ISSUE TITLE
[macOS] [Flyouts] All flyouts are out of alignment. content is displayed overlapping the left menu

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#119]
## Current behavior

![Screen Shot 2021-02-05 at 9 16 11 AM](https://user-images.githubusercontent.com/38770890/107045145-2e535a00-6793-11eb-8d1f-c6c0df4f9a93.png)
![Screen Shot 2021-02-05 at 9 16 28 AM](https://user-images.githubusercontent.com/38770890/107045157-33b0a480-6793-11eb-8dc9-c6cd3b221370.png)

## How to reproduce it (as minimally and precisely as possible)
1. Go to the left menu
2. Scroll and select Flyouts under Components section
3. Click on any button on the right - Flyghtout, Open, Options, or Help
4. Notice the flyouts are out of alignment

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Fixed by https://github.com/unoplatform/uno/pull/5170

**Comment by sakshi173** [comment]
Verified, Issue is fixed, closing.
![flyout issue](https://user-images.githubusercontent.com/74563602/118324239-c3bb6400-b4cf-11eb-9d92-146651adf5cb.png)
