### ISSUE TITLE
[macOS][Animation][RotateTransform + Opacity] Image display is cut off during animation

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#120]
## Current behavior
![Screen Shot 2021-02-05 at 10 48 20 AM](https://user-images.githubusercontent.com/38770890/107056111-fef71a00-679f-11eb-8f26-7fa44021b099.png)

## Expected behavior
The image must be fully displayed during the animation

## How to reproduce it (as minimally and precisely as possible)

1. From the left menu scroll to Features section
2. Click on Animations
3. Click on Start button from RotateTransform + Opacity section
4. Notice the Image is displayed cut off during the animation

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
@dr1rrb related to absolute origin of transforms?

**Comment by dr1rrb** [comment]
@carldebilly yes the animation is not the right one ... but with the element should not have been be clipped (and even if we fix the animation it will be visible)
