### ISSUE TITLE
[macOS][ComboBox] Content is aligned to the left when combobox is opened

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#123]
## Current behavior
![Screen Shot 2021-02-05 at 11 26 44 AM](https://user-images.githubusercontent.com/38770890/107061553-513b3980-67a6-11eb-9b0b-c7beeb4a4819.png)

## Expected behavior
![IMG_0122 2](https://user-images.githubusercontent.com/38770890/107061739-847dc880-67a6-11eb-95d5-a383d12bedc6.jpg)

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu scroll to Components section
2. Click on ComboBox
3. From the right side section Click on any arrow to display the combobox
4. Notice the ComboBox is aligned to the left

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Fixed by https://github.com/unoplatform/uno/pull/5170

**Comment by sakshi173** [comment]
Verified , Issue is fixed, closing.
![combobox fix issue](https://user-images.githubusercontent.com/74563602/118323214-4ba06e80-b4ce-11eb-88e9-1361c893cda8.png)
