### ISSUE TITLE
[macOS] [Hyperlink] Color and pressed state of the hyperlink is not displayed correctly

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#124]
## Current behavior
![Screen Shot 2021-02-05 at 11 45 44 AM](https://user-images.githubusercontent.com/38770890/107063879-e63f3200-67a8-11eb-9cb3-e3a12d2adf78.png)
![Screen Shot 2021-02-05 at 11 46 11 AM](https://user-images.githubusercontent.com/38770890/107063892-e9d2b900-67a8-11eb-8cf8-5f91ae1d4d88.png)

## Expected behavior
![IMG_0123](https://user-images.githubusercontent.com/38770890/107064039-14247680-67a9-11eb-926f-d00a505d66ae.jpg)

## How to reproduce it (as minimally and precisely as possible)

1. From the left menu under Theme section
2. Click on Material Palette or Fluent Palette
3. Scroll to the bottom of page
4. Notice the hyperlink color is not the correct
5. Click on the hyperlink
6. Notice when the hyperlink is pressed it is missing instead of becoming opaque

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by sakshi173** [comment]
Verified the issue is fixed, closing.
![hyperlink issue correct 2](https://user-images.githubusercontent.com/74563602/118318082-e4cb8700-b4c6-11eb-91cd-18702650d5ad.png)
![hyperlink issue correct](https://user-images.githubusercontent.com/74563602/118318108-ea28d180-b4c6-11eb-932f-5d7140e8a6ba.png)
