### ISSUE TITLE
[macOS] [Overview] RadioButton and ToggleSwich section are missing from Overview page

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#125]
## Current behavior
![Screen Shot 2021-02-05 at 12 20 59 PM](https://user-images.githubusercontent.com/38770890/107067581-78493980-67ad-11eb-8cbf-5ba1f070f65e.png)

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu select Overview section
2. Scroll to the bottom of the page
3. Notice unable to scroll to the bottom of the page

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Cannot reproduce on the lastest version in master (scroll bar shows up, so the samples can be revealed.
