### ISSUE TITLE
[macOS] [RadioButton] Checked radio button is not displaying correctly when clicked

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#128]
## Current behavior
<img width="601" alt="Screen Shot 2021-02-05 at 2 52 49 PM" src="https://user-images.githubusercontent.com/38770890/107086400-f3b7e480-67c7-11eb-8067-2d6976b4414f.png">

## Expected behavior
<img width="375" alt="Capture3" src="https://user-images.githubusercontent.com/38770890/107086495-1813c100-67c8-11eb-9891-ae04409d4fad.PNG">

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu select Overview
2. From the right side scroll on the page
3. Click on Checked RadioButton
4. Notice RadioButton is not displaying correctly 

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Fixed in Uno.Material. Waiting on new NuGet package to update Gallery with
