### ISSUE TITLE
[macOS] [Headers] Description is missing in multiple headers

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#129]
## Current behavior
<img width="919" alt="Screen Shot 2021-02-05 at 4 26 15 PM" src="https://user-images.githubusercontent.com/38770890/107091241-742e1380-67cf-11eb-802d-bda8c20c9e30.png">

<img width="909" alt="Screen Shot 2021-02-05 at 4 41 05 PM" src="https://user-images.githubusercontent.com/38770890/107092388-827d2f00-67d1-11eb-8384-4dcf24f1ec40.png">

<img width="1076" alt="Screen Shot 2021-02-05 at 4 43 51 PM" src="https://user-images.githubusercontent.com/38770890/107092392-85781f80-67d1-11eb-81b2-a1ca4ebe4225.png">

<img width="933" alt="Screen Shot 2021-02-05 at 4 44 06 PM" src="https://user-images.githubusercontent.com/38770890/107092454-a2145780-67d1-11eb-9b4b-24a671e4c3ac.png">

![Screen Shot 2021-02-06 at 8 22 36 PM](https://user-images.githubusercontent.com/38770890/107133722-33122e00-68b9-11eb-9c59-de315a261c6c.png)

## Expected behavior
<img width="795" alt="Capture4" src="https://user-images.githubusercontent.com/38770890/107091260-7e501200-67cf-11eb-9956-e3d2b7461e1c.PNG">

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu select Theme and Click on Typography
2. Notice the  description is missing in the header

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Relates to #130
