### ISSUE TITLE
[macOS] The Material/Fluent Header disappears when scrolling to the bottom

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#132]
## Current behavior

![Screen Shot 2021-02-06 at 6 49 06 PM](https://user-images.githubusercontent.com/38770890/107132680-0bb66380-68af-11eb-8f3b-f8c127226efe.png)

## Expected behavior
 - Header tabs must remain visible when scrolling on the page

<img width="795" alt="Capture7" src="https://user-images.githubusercontent.com/38770890/107132670-f93c2a00-68ae-11eb-9021-4af8f7e27f20.PNG">

## How to reproduce it (as minimally and precisely as possible)
1. Go to any page that contains the Material/Fluent header and scroll to the bottom
2. Notice the header is dismissed

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Fixed as of 3.5.0-dev.480 by https://github.com/unoplatform/uno/pull/5170
