### ISSUE TITLE
[UWP/WASM][Menu] The ExpandingBottomSheet  and ModalstandardBottomsheet item is cut off  from Burger menu

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#135]
## Current behavior
![burger list cut off issue](https://user-images.githubusercontent.com/74563602/107136258-b9d20580-68cf-11eb-8fe2-4be551b7ee47.png)

<img width="548" alt="Capture12" src="https://user-images.githubusercontent.com/38770890/107135050-9609c200-68c5-11eb-8e87-d5bb5cbff55b.PNG">

## Expected behavior
The item name must be fully displayed from the list

## How to reproduce it (as minimally and precisely as possible)

1. From the menu left select Components
2. Under Components section look for ExpandingBottomSheet item
3. Notice the item name is cut off

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by sakshi173** [comment]
Verified, Issue is fixed, closing
