### ISSUE TITLE
[macOS] [Components/Features] Footer information is missing on all pages in the Components and Features section

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#145]
## Current behavior

Footer information is missing on all pages in the Components and Features section

## Expected behavior
<img width="501" alt="Capture15" src="https://user-images.githubusercontent.com/38770890/107289620-51039e00-6a33-11eb-8c34-085a283e8074.PNG">

## How to reproduce it (as minimally and precisely as possible)

1. From the left menu select any item under Components or Features sections
2. Scroll to the bottom of the page
3. Notice the information with the link that redirects to the official documentation are missing at the bottom of the pages

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Got fixed by https://github.com/unoplatform/uno/pull/5183
