### ISSUE TITLE
[macOS] Able to scroll on the Menu when all sections are Collapsed 

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#146]
## Current behavior

https://user-images.githubusercontent.com/38770890/107290338-5ad9d100-6a34-11eb-9f7b-30c0e038d620.mov

## Expected behavior

The Menu should not be scrollable when the elements are not expanded

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
Should have been fixed by https://github.com/unoplatform/uno/pull/5322
