### ISSUE TITLE
[UWP][ExpandingBottomSheet] Expanding code box the Footer and Toggle minimal Sheet button overlaps

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#149]
## Current behavior

<img width="726" alt="Capture17" src="https://user-images.githubusercontent.com/38770890/107294699-e60a9500-6a3b-11eb-9937-aed976946a1f.PNG">

## Expected behavior

The Toggle Minimal Sheet button should be aligned a little higher on the page

## How to reproduce it (as minimally and precisely as possible)

1. From the menu left select Components
2. Click on ExpandingBottomSheet
3. From the right side Click on The expand code box
4. Notice the footer information overlap the Toggle Minimal Sheet button

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@sakshi173 Can you help to verify if this issue is still valid for Gallery please?

**Comment by sakshi173** [comment]
@agneszitte-nventive I am not sure is this valid or not as the expandingBottomsheet components is no more present in Gallery to verify . So we can close this bug. please let me know your views.

**Comment by agneszitte-nventive** [comment]
> @agneszitte-nventive I am not sure is this valid or not as the expandingBottomsheet components is no more present in Gallery to verify . So we can close this bug. please let me know your views.

Oh yeah, that's true! I will close it @sakshi173
