### ISSUE TITLE
[macOS][ListView] Custom Template sample is missing

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#160]
## Current behavior

![Screen Shot 2021-02-09 at 10 17 35 PM](https://user-images.githubusercontent.com/38770890/107461511-2b0bf580-6b28-11eb-9deb-5f5a853823cb.png)

## Expected behavior

<img width="794" alt="Capture19" src="https://user-images.githubusercontent.com/38770890/107461525-33643080-6b28-11eb-8223-22d8fb13b8d3.PNG">

## How to reproduce it (as minimally and precisely as possible)

1. From the left menu select Features section
2. Scroll on the list and Click on ListView
3. Notice the Custom Template sample is missing

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
This is fixed by updating to latest Uno
