### ISSUE TITLE
[macOS][TexBox] TextBox does not become highlighted when focusing on the predefined text

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#162]
## Current behavior

https://user-images.githubusercontent.com/38770890/107465428-54308400-6b30-11eb-8965-7acbab926e48.mov

## Expected behavior

When I click on any section in the textBox it becomes highlighted

## How to reproduce it (as minimally and precisely as possible)

1. From the left menu select Overview
2. Put the focus on any TextBox around the  predefined text
3. Notice the TexBox does not become highlighted

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by ajpinedam** [comment]
fixed in PR https://github.com/unoplatform/uno/pull/5201
