### ISSUE TITLE
[macOS][Dark Mode] Some texts are not visible. The texts are in black font

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#173]
## Current behavior

![Screen Shot 2021-02-12 at 9 15 20 AM](https://user-images.githubusercontent.com/38770890/107785223-50605580-6d1a-11eb-86e4-c8a0ca9ae74c.png)

## Expected behavior

The texts Should be displayed in white font

## How to reproduce it (as minimally and precisely as possible)

Notice the Overview page

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
Seems to be fixed in latest Uno.Gallery (which is using Uno 3.7.0-dev.18)

![image](https://user-images.githubusercontent.com/8270914/112617760-c5d04300-8dfb-11eb-9a62-bfaa0343b9db.png)
