### ISSUE TITLE
[macOS][Menu] The way the arrows point when items are collapsed or expanded is incorrect

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#175]
## Current behavior

https://user-images.githubusercontent.com/38770890/107800122-64ad4e00-6d2c-11eb-9578-3e8398e5fe2f.mov

## Expected behavior

![arrow](https://user-images.githubusercontent.com/38770890/107800361-b229bb00-6d2c-11eb-975b-428d556a4b08.png)

## How to reproduce it (as minimally and precisely as possible)

1. Click the arrows in the menu to expand and collapse the items in the list
2. Notice that the arrows do not point in the correct direction

**Note:** Sometimes are working fine but then they lose the functionality

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Fixed in latest
