### ISSUE TITLE
[Uno Gallery] - Overview Checkbox & Radio Button - Wrong Font

### ISSUE THREAD

**Issue by marklevasseur88** [unoplatform/Uno.Gallery#245]
## Current behavior
The example font doesn't appear correctly, the font appears as Times.

## Expected behavior
The example font should be Roboto

## How to reproduce it (as minimally and precisely as possible)

Open https://gallery.platform.uno/ in Chrome or Safari scroll to the Checkbox and Radio Button section.

<img width="605" alt="Screen Shot 2021-05-18 at 2 09 34 PM" src="https://user-images.githubusercontent.com/81247387/118703288-ee652f80-b7e3-11eb-8bcc-91efc74c1e39.png">

## Environment
Mac OS Big Sur - Chrome
Mac OS Big Sur - Safari

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@sakshi173 Can you help to verify if this issue is still valid for Gallery please?

**Comment by sakshi173** [comment]
@agneszitte-nventive, I verified this issue is fixed in the current build due to that closing it.

**Comment by agneszitte-nventive** [comment]
> @agneszitte-nventive, I verified this issue is fixed in the current build due to that closing it.

Thanks a lot @sakshi173 !
