### ISSUE TITLE
Add Accelerometer sample

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#31]
## What would you like to be added:

Show the capabilities of `Accelerometer`

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

**Comment by morning4coffe-dev** [comment]
Done https://github.com/unoplatform/Uno.Gallery/pull/469
