### ISSUE TITLE
Add JumpList sample

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#32]
## What would you like to be added:

Sample page for the `JumpList` API. 

## Why is this needed:

To show how to create app shortcuts on iOS, Android and Windows.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

**Comment by morning4coffe-dev** [comment]
Duplicate of #483
