### ISSUE TITLE
Improve `NetworkInformation` sample

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#33]
## What would you like to be added:

Sample for the `NetworkInformation` API.

## Why is this needed:

To show how to observe network changes and check for network connectivity.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly Renderers for Xamarin.Forms
- [x] Windows

**Comment by morning4coffe-dev** [comment]
The Gallery sample has the requested features already implemented. But I have added more details into the docs.
