### ISSUE TITLE
[Android][NavigationView] Burger menu is displayed as characters

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Gallery#34]
## Current behavior

![Uno Gallery characters](https://user-images.githubusercontent.com/49959074/94202806-5ac5a400-fe8c-11ea-9a8a-2c7a30b49f8b.png)

## Expected behavior

Burger menu icon should be visible

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Notice that the burger menu is displayed incorrectly

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Fixed in latest version of Gallery

**Comment by sakshi173** [comment]
Issue is fixed in latest canary.
