### ISSUE TITLE
[Gallery] Migrate to WinUI/WinAppSDK

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#399]
### Current behavior

![progressring ‎- Photos](https://user-images.githubusercontent.com/74563602/179602275-dd5562e0-8464-4262-928d-142c0c7160c7.png)
![Lottie ‎- Photos](https://user-images.githubusercontent.com/74563602/179602291-4e779b40-462a-443d-a2f6-9c658246d3e5.png)

### Expected behavior

![progressring correct](https://user-images.githubusercontent.com/74563602/179602621-f9306f55-6434-45ba-86e0-a9518d4b2dcb.png)
![Lottie ‎correct](https://user-images.githubusercontent.com/74563602/179602744-e7fdd635-4a57-4345-938a-ba986c3f63fd.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Progress Ring/Bar" from the "Component" list.
4. Observe that  'ProgressRing/Bar'  is missing.
5. Click "Lottie" from the "Features" list.
6. Observe that  'Lottie'  is missing.

### Affected platforms

iOS, Android

**Comment by kazo0** [comment]
Currently blocking the x64 build because of [this](https://github.com/CommunityToolkit/Lottie-Windows/issues/515)

**Comment by kazo0** [comment]
App fails to build in release for net7.0-ios as a result of https://github.com/dotnet/runtime/issues/90032

Current workaround is to add this to the .Mobile.csproj

```xml
<ItemGroup Condition="'$(Configuration)'=='Release'">
	<TrimmableAssembly Include="CommunityToolkit.WinUI.UI" />
</ItemGroup>
```

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.
