### ISSUE TITLE
[iOS][Android][CheckBox][Material] A checkmark appears in the CheckBox regardless of state

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Gallery#44]
## Current behavior

![Mobile CheckBox](https://user-images.githubusercontent.com/49959074/94736474-4543f480-033a-11eb-8a38-034ce7dff30f.gif)

## Expected behavior

![UWP CheckBox](https://user-images.githubusercontent.com/49959074/94736208-dc5c7c80-0339-11eb-8ae6-91a3d94ac00a.gif)

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Navigate to CheckBox
3. Select Material tab
4. Tap the checked CheckBox
5. Notice the CheckBox should be unchecked, however a checkmark appears

## Environment

iPhone X iOS 14.0.1
Samsung S10e Android 10

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by sakshi173** [comment]
Verified for the below version, Issue is fixed and closing.
Version 1.4.3 (763) for iOS
Version 1.4.3 (400759) for Android
