### ISSUE TITLE
[iOS][Android][TextBox][PasswordBox] Placeholder text animation speed is too slow, placeholder text overlaps with text entered

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Gallery#45]
## Current behavior

![TextBox Animation](https://user-images.githubusercontent.com/49959074/94738016-c8664a00-033c-11eb-9153-977d1e198826.gif)

## Expected behavior

![TextBox Animation UWP](https://user-images.githubusercontent.com/49959074/94738022-cbf9d100-033c-11eb-898d-b38c40bcf297.gif)

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Navigate to TextBox
3. Enter text to a TextBox
4. Notice that the placeholder text animation is slow and overlaps with the entered text

**NOTE**
Issue is also present when entering text to a PasswordBox

## Environment

iPhone 8 iOS 13.3
Samsung S10e Android 10

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
Behavior does not follow the Material Design guidelines also for all platform
![c582f2258c6521c270abae740a661180](https://user-images.githubusercontent.com/16295702/119697989-c8acdb80-be1e-11eb-91bd-ae68a88e86f7.gif)

**Comment by jeromelaban** [comment]
@agneszitte-nventive did we alter the behavior mentioned in this issue?

**Comment by agneszitte-nventive** [comment]
@jeromelaban the translate transform for the placeholder is done directly in visual states of the textbox style and needs to be reviewed apparently (maybe also the transform is not behaving the same for ios/android in terms of speed).
Needs more tests and investigation.

https://github.com/unoplatform/Uno.Themes/blob/58cbfb1eedb446c7cefd88e7a2f8c04283f45eed/src/library/Uno.Material/Styles/Controls/TextBox.xaml#L142

**Comment by agneszitte-nventive** [comment]
@sakshi173 Can you help to verify if this issue is still valid for Gallery please?

**Comment by sakshi173** [comment]
Hi @agneszitte-nventive, I retested this issue and I am not able to generate it, due to that closing it.

**Comment by agneszitte-nventive** [comment]
> Hi @agneszitte-nventive, I retested this issue and I am not able to generate it, due to that closing it.

Thanks a lot @sakshi173 !
