### ISSUE TITLE
[Uno Gallery] Add sample for `NumberBox` control

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#450]
## What would you like to be added:

UI samples for `NumberBox` in Uno Gallery

## Why is this needed:

Control samples

## For which Platform:

All

**Comment by blouflashdb** [comment]
Can I get more information for this issue? I would like to do it.

**Comment by MartinZikmund** [comment]
@blouflashdb Hi! The goal of each of these issues is to create a new sample page in Uno Gallery that demonstrates each control - in this case `NumberBox`. Because we don't have specific Material/Cupertino style for it yet, it will be enough to showcase the Fluent style. And ideally the sample should show several examples of what `NumberBox` can do. You can use the WinUI Gallery app as inspiration:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1075116/192626141-43598c8f-e930-4393-9fe4-c6e79065f8fc.png">

If you want to do this, I will assign the issue to you 👍 !

**Comment by blouflashdb** [comment]
Sure I would like to work on it. Thanks for the information.

**Comment by MartinZikmund** [comment]
@blouflashdb Assigned, let me know if you need any further info 👍 !

**Comment by riccikl** [comment]
@blouflashdb Are you still working on it? If not I would like to take it over

**Comment by blouflashdb** [comment]
@riccikl go for it. I had no time to do it yet.
