### ISSUE TITLE
[Uno Gallery] Add sample for `InfoBadge` control

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#451]
## What would you like to be added:

UI samples for `InfoBadge` in Uno Gallery

## Why is this needed:

Control samples

## For which Platform:

All

**Comment by lleibovich** [comment]
Hi, I would like to work on this issue. May I have a go at it?

**Comment by MartinZikmund** [comment]
@lleibovich also assigned 🤞
