### ISSUE TITLE
[Uno Gallery] Add sample for `RelativePanel` control

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#453]
## What would you like to be added:

UI samples for `RelativePanel` in Uno Gallery

## Why is this needed:

Control samples

## For which Platform:

All

**Comment by riccikl** [comment]
Hey, I would like to give it a try. I've seen that there is already a sample page for panels which includes the reative panel. Is the idea to create a separate page which showcases the different alignment functionalities?

**Comment by MartinZikmund** [comment]
@riccikl Also good! Assigned the issue 👍

**Comment by riccikl** [comment]
I just created a PR for the RelativePanel. Should the other panel types that are currently on the panel sample page also get their own sample page? I didn't see issues on the project board for those.

**Comment by riccikl** [comment]
@MartinZikmund You can close this issue now that the PR is merged.

And do you have any ideas for the other panel types?

**Comment by MartinZikmund** [comment]
@riccikl It would definitely be nice to have separate samples for `Grid`, `StackPanel` and `VariableSizedWrapGrid` - each could include samples even for advanced properties like `ColumnSpacing` etc.

**Comment by MartinZikmund** [comment]
@riccikl added #562 and #563
