### ISSUE TITLE
[Uno Gallery] Add sample for `PagerControl` control

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#454]
## What would you like to be added:

UI samples for `PagerControl` in Uno Gallery

## Why is this needed:

Control samples

## For which Platform:

All

**Comment by riccikl** [comment]
I have tried to work on it, but it seems that PagerControl is currently not working on UWP

**Comment by mcNets** [comment]
The is already a PagerControlPage. Do you need more samples?

**Comment by morning4coffe-dev** [comment]
You're right! I think the current sample showcases the control well enough.
