### ISSUE TITLE
[Uno Gallery] Add sample for `BreadcrumbBar` control

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#456]
## What would you like to be added:

UI samples for `BreadcrumbBar` in Uno Gallery

## Why is this needed:

Control samples

## For which Platform:

All

**Comment by trishitapingolia** [comment]
Hey, i would like to work on this issue. Could you give some details?

**Comment by MartinZikmund** [comment]
@trishitapingolia Thanks! The point of the issue is to add a sample page in the gallery app that demonstrates the features of `BreadcrumbBar`. In this case the control has only fluent style, which makes things simpler. You can check some of the other UI control sample pages to see how we usually structure them - essentially provide 2-4 "sections" each showcasing the control with some specific properties set
