### ISSUE TITLE
Add sample for `Clipboard`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#464]
## What would you like to be added:

Uno Gallery sample on using `Clipboard` . See https://unexpectedapis.azurewebsites.net/ for example

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by trungnt2910** [comment]
![image](https://user-images.githubusercontent.com/57174311/193306239-77aaf323-2f79-41ca-9f4c-88416f26efc7.png)

https://github.com/trungnt2910/ClipboardTest

Is this sample OK?

It's basically the Sample App I used back when I was testing Skia.Wpf/Gtk clipboard APIs.
Please assign me to this issue if you think this should be included in the sample app.

**Comment by MartinZikmund** [comment]
@trungnt2910 yes, this does seem to cover a lot of scenarios , however in case of the Gallery app, please adjust the layout to fit more into the Uno Gallery structure (several samples in a vertical scrollable layout, each showcasing a set of features)

**Comment by trungnt2910** [comment]
I've cleaned up my sample code and ported it to a Gallery page like this:
![image](https://user-images.githubusercontent.com/57174311/193400544-05aec4bb-4157-42f3-b314-2697fdb0a79e.png)

Check out the linked pull request for more details.
