### ISSUE TITLE
Add sample for `Magnetometer`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#470]
## What would you like to be added:

Uno Gallery sample on using `Magnetometer` . In a similar manner as `Accelerometer` sample on https://unexpectedapis.azurewebsites.net/

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by ktos** [comment]
This looks in line of Accelerometer and HingeAngleSensor, I can take it.
