### ISSUE TITLE
Add sample for `Lamp`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#471]
## What would you like to be added:

Uno Gallery sample on using `Windows.Devices.Lights.Lamp` https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/Devices/Lights

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by ktos** [comment]
Checked it out and it doesn't look problematic, I will take this one as well :)
