### ISSUE TITLE
Add sample for `VibrationDevice`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#472]
## What would you like to be added:

Uno Gallery sample on using `VibrationDevice` API . See https://unexpectedapis.azurewebsites.net/ for example

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by TopperDEL** [comment]
I want to tackle this one :)

**Comment by TopperDEL** [comment]
Hm, the API seems to be different now. Martin, the Vibration on your page does not work on my end. And it seems the VibrationDevice.Vibrate-Method is not valid anymore. I guess I need to use the coding from the [Haptics-Section](https://platform.uno/docs/articles/features/windows-devices-haptics.html)? The [Vibration](https://platform.uno/docs/articles/features/windows-phone-devices-notification-vibrationdevice.html) seems to be outdated? Or am I missing a special Namespace here? Intellisense does not give me another `VibrationDevice`-class.

**Comment by TopperDEL** [comment]
![image](https://user-images.githubusercontent.com/1833242/194827235-ed5dd318-5972-4454-a754-9333780dea81.png)

Hm, not sure what I'm doing wrong here. It does not compile though I see the class implemented in the Uno-repo...

**Comment by MartinZikmund** [comment]
@TopperDEL The API should be available in UWP when the Mobile SDK reference is added - 

![image](https://user-images.githubusercontent.com/1075116/196119826-36b143dd-8528-4fc9-a2f1-e41b3280fe27.png)

On the other hand, the sample will not work on any Windows device (until Windows Phone comes back  😁 ), so it can also be just blocked by `#if HAS_UNO`

**Comment by TopperDEL** [comment]
Thanks! I've disabled the sample for !HAS_UNO.
