### ISSUE TITLE
Add sample for `Barometer`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#474]
## What would you like to be added:

Uno Gallery sample on using `Barometer` API . See https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/Devices/Sensors

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by donheshanthaka** [comment]
Hey there can you assign me this issue as well :)

**Comment by muhmuhhum** [comment]
Hi i would love to work on this feature pls assign it to me

**Comment by muhmuhhum** [comment]
Ok just checked there is already an open pr with this implemented [https://github.com/unoplatform/Uno.Gallery/pull/698](https://github.com/unoplatform/Uno.Gallery/pull/698)

**Comment by MartinZikmund** [comment]
@morning4coffe-dev is there a sensor which does not have a sample yet and @muhmuhhum could take? Maybe Compass?

**Comment by morning4coffe-dev** [comment]
@MartinZikmund `Compass` would be great! Also, I think `ProximitySensor` for Android is not yet done. @muhmuhhum I will create issues for those, let me know if you want to get assigned on either of those

**Comment by agneszitte** [comment]
@morning4coffe-dev I am closing this issue as the work was done with https://github.com/unoplatform/Uno.Gallery/pull/698
