### ISSUE TITLE
Add sample for `Gyrometer`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#475]
## What would you like to be added:

Uno Gallery sample on using `Gyrometer` API . See https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/Devices/Sensors

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by donheshanthaka** [comment]
Hey there can you assign me this issue as well :)

**Comment by muhmuhhum** [comment]
Hi i would love to work on this feature pls assign it to me

**Comment by muhmuhhum** [comment]
Ok just checked and this is already merged maybe close this issue Completed in [https://github.com/unoplatform/Uno.Gallery/pull/706](https://github.com/unoplatform/Uno.Gallery/pull/706) i think.

**Comment by MartinZikmund** [comment]
Ah yes, sorry, should have been closed
