### ISSUE TITLE
Add sample for `HingeAngleSensor`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#476]
## What would you like to be added:

Uno Gallery sample on using `HingeAngleSensor` API . See https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/Devices/Sensors

## Why is this needed:

Developer samples

## For which Platform:

Android

**Comment by ktos** [comment]
I think I can try implementing it as I even have a Surface Duo to test it out :)
