### ISSUE TITLE
Add sample for `SimpleOrientationSensor`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#479]
## What would you like to be added:

Uno Gallery sample on using `SimpleOrientationSensor` API . See https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/Devices/Sensors

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by TopperDEL** [comment]
I want to tackle this :)
