### ISSUE TITLE
Add sample for `PowerManager` API

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#480]
## What would you like to be added:

Uno Gallery sample on using `PowerManager` API . See https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/System/Power

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by trungnt2910** [comment]
Let me complete this issue please, probably useful for testing any future `PowerManager` implementation attempts.
