### ISSUE TITLE
Add sample for `DisplayRequest` API

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#481]
## What would you like to be added:

Uno Gallery sample on using `DisplayRequest` API . See https://unexpectedapis.azurewebsites.net/ for example, https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/System/Display

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by TopperDEL** [comment]
I would like to tackle this next.
