### ISSUE TITLE
Add sample for `EmailManager`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#485]
## What would you like to be added:

Uno Gallery sample on using `EmailManager` API . See https://github.com/unoplatform/uno/tree/master/src/Uno.UWP/ApplicationModel/Email

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by lleibovich** [comment]
Hi, I would like to work on this issue. May I have a go at it?

**Comment by MartinZikmund** [comment]
@lleibovich Definitely, assigned to you, thanks! Let me know if anything is needed 👍
