### ISSUE TITLE
Add sample for `LocalSettings` API

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#492]
## What would you like to be added:

Uno Gallery sample on using `ApplicationData.Current.LocalSettings` API . See https://platform.uno/docs/articles/features/settings.html

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by TopperDEL** [comment]
I want to tackle this one.

**Comment by TopperDEL** [comment]
As `RoamingSettings` are not roamed anymore, should I mention them in the sample anyway? Or should the sample be restricted to LocalSettings?

**Comment by MartinZikmund** [comment]
@TopperDEL Feel free to include only `LocalSettings`, as both behave identically anyway.
