### ISSUE TITLE
Add sample for `PhoneCallManager` API

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#493]
## What would you like to be added:

Uno Gallery sample on using `PhoneCallManager` API . See https://platform.uno/docs/articles/features/windows-applicationmodel-calls.html

## Why is this needed:

Developer samples

## For which Platform:

All

**Comment by ktos** [comment]
I'd like to take this one :)

**Comment by MartinZikmund** [comment]
@ktos Assigned, let me know if you need anything 👍 !
