### ISSUE TITLE
Add sample for `Gamepad` API

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#501]
## What would you like to be added:

Uno Gallery sample for Gamepad API

## Why is this needed:

Demonstrating how to connect and receive Gamepad readings

## For which Platform:

All

**Comment by Jadhielv** [comment]
Hi, I would like to work on this issue.

**Comment by MartinZikmund** [comment]
@Jadhielv assigned, let me know if you need anything 👍
