### ISSUE TITLE
[WASM][Toggle Light/Dark] Toggle does not have rounded corners

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/Uno.Gallery#55]
## Current behavior

Light/Dark theme toggle does not have rounded corners for WASM

![image](https://user-images.githubusercontent.com/16295702/97323226-f315c680-1846-11eb-9d83-7e594881bfc9.png)

## Expected behavior

Toggle Light/Dark theme toggle should have rounded corners for WASM

![image](https://user-images.githubusercontent.com/16295702/97323990-b72f3100-1847-11eb-8fdc-48ba29e7984a.png)

## How to reproduce it (as minimally and precisely as possible)

Launch Uno Gallery and notice the Light/Dark theme toggle.

## Environment

**Devcies:**

**Nuget Package:** Uno.UI

**Package Version(s):** latest dev

**Affected platform(s):**

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

## Anything else we need to know?

Missing overflow: hidden; for the Grid.
![image](https://user-images.githubusercontent.com/16295702/97323780-83540b80-1847-11eb-82b3-3fc2b84cb14d.png)

**Comment by jeromelaban** [comment]
This is fixed in latest Uno @carldebilly, isn't it ?

**Comment by agneszitte-nventive** [comment]
@jeromelaban it was fixed for Border but not for Grid normally if I'm not mistaking @carldebilly

**Comment by agneszitte-nventive** [comment]
@carldebilly is also looking at this issue at the same time => https://github.com/unoplatform/Uno.Gallery/issues/37
