### ISSUE TITLE
Selection Mode dropdown breaks after second open 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/Uno.Gallery#647]
## Current behavior
Selection Mode dropdown breaks its content after the second open.

## How to reproduce it (as minimally and precisely as possible)
Open CalendarView page and start clicking on the Selection Mode dropdown a few times.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://user-images.githubusercontent.com/78549750/221650337-26140180-8f41-485e-ac6a-885df007c411.mp4

**Comment by jeromelaban** [comment]
Thanks for the report! Could you indicate which platform it is?

**Comment by morning4coffe-dev** [comment]
@jeromelaban Only on WASM, on Windows it seems to be fine and on Android and the CalendarView is not present.

**Comment by jeromelaban** [comment]
This issue seems similar to https://github.com/unoplatform/uno/issues/11514.
