### ISSUE TITLE
Add search feature for Gallery samples

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/Uno.Gallery#648]
## What would you like to be added:
A search feature for the samples in Gallery similar to the one in WinUI Gallery. 

## Why is this needed:
That would increase overall usability and make navigating across the app much faster.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

## Anything else we need to know?
![image](https://user-images.githubusercontent.com/78549750/221968564-68d09eb6-1882-47d3-807c-41124bfd3923.png)

**Comment by MartinZikmund** [comment]
Sounds good!

**Comment by morning4coffe-dev** [comment]
The implementation of the Search is done. For the Search terms there is a separate issue #667
