### ISSUE TITLE
extract control example + adjustable options + adaptive visual-state into a reusable control

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Gallery#766]
## What would you like to be added:
ControlExample from toolkit: [cs](https://github.com/unoplatform/uno.toolkit.ui/blob/main/samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/ControlExample.cs) + [xaml](https://github.com/unoplatform/uno.toolkit.ui/blob/main/samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Styles/ControlExample.xaml)

## Why is this needed:
In various pages (like: [InfoBadgeSamplePage.xaml](https://github.com/unoplatform/Uno.Gallery/blob/master/Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml)), we are copy-pasting the control+options setup with UserControl+VisualState to make then mobile friendly which is a lot of boiler plate code. And worse yet, this all boilerplate code is within the XamlDisplay wrapper.

## Anything else we need to know?

**Comment by morning4coffe-dev** [comment]
Completed via https://github.com/unoplatform/Uno.Gallery/pull/803
