### ISSUE TITLE
Add Lightweight Styling Sample Page

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#824]
As a result of the work for the [Lightweight Styling](https://github.com/unoplatform/Uno.Themes/issues/854) for Themes and Toolkit, we need to highlight this with some sort of sample page in the Gallery

Perhaps a display similar to the OverviewPage where you can toggle or use the color picker to override brushes for certain controls in certain visual states

**Comment by silviuo** [comment]
I've just rebased off of main and I'm currently trying to fix an exception locally

**Comment by silviuo** [comment]
I closed PR #830 and created a cleaner one #847
