### ISSUE TITLE
[Gallery][Android] NumberBox-Description text is truncating for 'Simple Numberbox' section.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#895]
### Current behavior

![Numberbox ‎- Photos](https://user-images.githubusercontent.com/74563602/204365348-9325dbe9-bbe6-4e53-ad11-cab4a106452a.png)

### Expected behavior

![Numberbox ‎- correct](https://user-images.githubusercontent.com/74563602/204366042-da652f8f-60e1-4ca6-8723-d4fccf6e90e0.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right .
3. Go to 'UI Components' section.
4. Click on Number Box option.
5. Go to 'A Simple NumberBox' section
6. Observe that the text 'This is a description which is shown below the numberbox'  is truncating from the last and full text is not visible.

### Affected platforms

Android

**Comment by agneszitte** [comment]
@sakshi173 can you test if this issue is still happening with latest canary please

**Comment by sakshi173** [comment]
@agneszitte, this issue is present in portrait mode, but when change mode as landscape the text correctly displaying. Please let me know your views on this defect. attached below the screenshot for landscape mode.
![numberbox](https://github.com/unoplatform/Uno.Gallery/assets/74563602/7c446cd6-9c32-46d4-9134-50d5d4509fcd)

**Comment by agneszitte** [comment]
I have opened an issue on the Microsoft repo microsoft/microsoft-ui-xaml#8998.
We will do a workaround for Gallery

**Comment by sakshi173** [comment]
Verified this issue is fixed , closing it
