### ISSUE TITLE
[Android][iOS][Shadow/TabBar] TabBarItem StateLayer displaying wrong color

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/Uno.Gallery#899]
## Current behavior
![image](https://github.com/unoplatform/Uno.Gallery/assets/114886335/43571eea-42ff-4cb6-92f9-73c6d485b995)

## Expected behavior
![image](https://github.com/unoplatform/Uno.Gallery/assets/114886335/9745d777-f712-4da1-ae34-e7b109e0af5e)

## Environment

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by agneszitte** [comment]
Related PR for backport https://github.com/unoplatform/Uno.Gallery/pull/916
