### ISSUE TITLE
[Gallery][iOS/Android]SwipeControl- The symbol for 'Unmark' option is incorrect for 'Swipe to reveal actions' option.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#900]
### Current behavior

![symol issue](https://user-images.githubusercontent.com/74563602/220817936-c9d2f542-b9d2-4353-8771-07c295497e61.png)

### Expected behavior

Correct symbol should display.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "SwipeControl" from the "UI Components" list.
4. Swipe right side on the 'Swipe to reveal actions' option.
5. Click on the flag symbol.
6. Now again swipe on the right side.
7. Observe that symbol for 'Unmark' option is incorrect.

### Works on UWP/WinUI

None

### Affected platforms

iOS

**Comment by agneszitte** [comment]
@sakshi173 can you verify if the icon is fixed with the latest canary please

**Comment by sakshi173** [comment]
Verified, issue is fixed, closing it.
