### ISSUE TITLE
[Gallery][iOS/Android/] Checkbox, Radio button and Toggleswitch- For label, discrepancy in font size.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#901]
### Current behavior

![font issue](https://user-images.githubusercontent.com/74563602/220814769-fbc0ab9e-d493-4065-b54a-bbc4c417bee8.png)

### Expected behavior

![font correct](https://user-images.githubusercontent.com/74563602/220814860-2a37f364-66bb-418b-af19-71d455f371f0.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Click on 'Overview' option.
4. Notice that font size is different for Toggleswitch and Radiobutton.

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

**Comment by agneszitte** [comment]
Re-Open for https://github.com/unoplatform/Uno.Themes/pull/1167

**Comment by agneszitte** [comment]
Re-Open for next changes for https://github.com/unoplatform/Uno.Gallery/pull/884 and backport PRs for https://github.com/unoplatform/Uno.Themes/pull/1167

**Comment by agneszitte** [comment]
Re-Open for backports
