### ISSUE TITLE
[Neumorphism][Light Theme] ComboBox selected option should be a different color than the label

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#913]
**ComboBox Light theme only**
The selected option should be a different color then the label, you can refer to TextBox with Input for Values

Tested on WASM, probably an issue on other platforms as well

Light (incorrect)
![image](https://github.com/unoplatform/Uno.Gallery/assets/29584087/c7f8d3f2-a3dd-400f-bb1b-c9396ab194d9)

Dark (Correct)
![image](https://github.com/unoplatform/Uno.Gallery/assets/29584087/4c60a781-49c8-4741-8088-e1df8183b7a8)

_Originally posted by @NVLudwig in https://github.com/unoplatform/Uno.Gallery/issues/903#issuecomment-1692331870_

**Comment by agneszitte** [comment]
Re-Open issue (needs to verify if there is not something left for this so we can close #922 as work has been done in #944)
