### ISSUE TITLE
[Neumorphism] ToggleSwitch knobs are the wrong color

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#914]
Toggle Switch Thumbs (aka knobs) are the wrong colors (both Light and Dark)

Tested on WASM, probably an issue on other platforms as well

Current
<img width="154" alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/29584087/1b0c78a2-b4e3-4343-8aa3-1882d1f237af"> 

Expected 
<img width="118" alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/29584087/4a3c8ef4-c51e-4b61-ad97-e9c6da772c46">

_Originally posted by @NVLudwig in https://github.com/unoplatform/Uno.Gallery/issues/903#issuecomment-1695903105_

**Comment by eriklimakc** [comment]
Updating Toolkit packages to `4.0.0-dev.88` should fix it.

**Comment by agneszitte** [comment]
> Updating Toolkit packages to `4.0.0-dev.88` should fix it.

@eriklimakc if you can please verify tomorrow and let us know
