### ISSUE TITLE
More info at NavigationView Page

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/Uno.Gallery#934]
## What would you like to be added:

To follow the pattern of the rest of the gallery, would be nice to have the xaml example of the NavigationView usage.
Right now, the page just says it is the control we have at left. No way to see any Xaml Code.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by morning4coffe-dev** [comment]
@iurycarlos Great suggestion! But it is a duplicate of https://github.com/unoplatform/Uno.Gallery/issues/589

**Comment by iurycarlos** [comment]
Thanks! Closing as duplicate of #589
