### ISSUE TITLE
[Shadows] Update styling of Shadow Builder sample

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#935]
Should look more like [proposed designs](https://www.figma.com/file/yrIxOBFdnzGVCdgTcl0gsH/Shadow-Playground?type=design&node-id=569-86765&mode=design&t=Mmpa993oCXbG7mwp-0) 

<img width="244" alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/4793020/1b763c2b-506a-4fcd-bbb1-b343ff24796d">

**Comment by agneszitte** [comment]
Re-Open for backport
