### ISSUE TITLE
[Skia (?Other Platforms)][Neumorphic][TabBar] Selecting "TabBar" in the sample list and then selecting any other item causes the app to crash

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/Uno.Gallery#939]
## Current behavior

NeumorphicControlCombo selecting "TabBar" in the sample list and then selecting any other item causes the app to crash:
`System.NullReferenceException    HResult=0x80004003    Message=Object reference not set to an instance of an object.    Source=Uno.UI    StackTrace:     at Microsoft.UI.Xaml.Controls.MenuFlyout.OnClosed() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.cs:line 193`

## Expected behavior

No crash

## How to reproduce it (as minimally and precisely as possible)

Current branch where it can be tested:
https://github.com/unoplatform/Uno.Gallery/tree/dev/xygu/20230830/neumorphic-2nd-pass

## Environment

Nuget Package: Uno.Toolkit

Package Version(s): https://www.nuget.org/packages/Uno.Toolkit/5.0.0-dev.94

Affected platform(s):

- [X] Skia
- [?] Other platforms need to be tested, please

**Comment by jeromelaban** [comment]
I'm not able to reproduce the condition in the sample app at this time, it could be a scenario specific to the AppBar.

**Comment by agneszitte** [comment]
Re-Open for backports

**Comment by sakshi173** [comment]
@agneszitte, I tried in Skia.GTK for both 5x and 4X and not able to reproduce this issue, please let me know if I can close it.

**Comment by agneszitte** [comment]
> @agneszitte, I tried in Skia.GTK for both 5x and 4X and not able to reproduce this issue, please let me know if I can close it.

Can you please test the other platforms also just in case? If it not reproducible on all platforms then we can close this issue

**Comment by sakshi173** [comment]
I am not able to reproduce this defect for any platform due to that closing it.
