### ISSUE TITLE
Match header menu with main Uno Platform site

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#945]
New Uno Platform site header menu
<img width="708" alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/4793020/eb44e705-c339-46d0-a4e9-4428c26369d4">
Current Gallery header menu
<img width="708" alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/4793020/225b0eb9-88c7-4f48-a274-8b47d7257822">

Gallery should be updated to match the current Uno main site header

**Comment by kazo0** [comment]
fyi @sasakrsmanovic

**Comment by Arieldelossantos** [comment]
hey @kazo0 / @sasakrsmanovic i've started working on this enhancement and brought some questions...
which button do we want to include?? all of them?? Platforms-Tools-Resources are flyout buttons with sub menus...

**Web**

![Image](https://github.com/unoplatform/Uno.Gallery/assets/34275909/06a63fd1-a9bd-42f1-b5fd-66debfea55fe)

**Uno App (After partial change)**

![Image](https://github.com/unoplatform/Uno.Gallery/assets/34275909/1cb2fc13-b234-47f7-aa1d-da7c529758dd)

**Comment by kazo0** [comment]
> hey @kazo0 / @sasakrsmanovic i've started working on this enhancement and brought some questions...
> which button do we want to include?? all of them?? Platforms-Tools-Resources are flyout buttons with sub menus...
> 
> **Web**
> 
> ![Image](https://github.com/unoplatform/Uno.Gallery/assets/34275909/06a63fd1-a9bd-42f1-b5fd-66debfea55fe)
> 
> **Uno App (After partial change)**
> 
> ![Image](https://github.com/unoplatform/Uno.Gallery/assets/34275909/1cb2fc13-b234-47f7-aa1d-da7c529758dd)
> 
> 

cc @NVLudwig

**Comment by agneszitte** [comment]
@kazo0 we will check today on the priority on this as we have a little list of Gallery improvements that I want to make sure we can keep them for later on (to do them all at once) and focus on the upcoming new release
