### ISSUE TITLE
[Android][Neumorphism][ComboBox] Items only displayed if arrow is clicked

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/Uno.Gallery#971]
## Current behavior

Items should popup when combobox is pressed anywhere within the control bounds

https://github.com/unoplatform/Uno.Gallery/assets/114886335/010b36a9-c682-4240-a228-6beafa8244fe

## Expected behavior

Like the other platforms:

https://github.com/unoplatform/Uno.Gallery/assets/114886335/c265f36d-fafb-422a-9148-2749d8a1272d

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by agneszitte** [comment]
Re-Open for backport
