### ISSUE TITLE
[Shadow Builder] Can we remove or optimize the third shadow presented by default

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Gallery#983]
## What would you like to be added:
Remove the green inner shadow or use settings that don't bleed into the inputs

## Why is this needed:
Discoverability and presentation.
The shadow builder is quite tall and having 3 shadows means not seeing the content below when browsing from laptop or smaller form factors. It's also quite busy visually.

If it's a business requirement to have 3 shadows can we make the third one a bit less noisy.

**3 VS 2 shadows**

<img width="1245" alt="2 Shadows" src="https://github.com/unoplatform/Uno.Gallery/assets/29584087/61ed0ac3-20d4-44b9-90fc-5f1cdc4e7cde">

**3 shadows Now VS tweaked**

<img width="1248" alt="3 shadow options" src="https://github.com/unoplatform/Uno.Gallery/assets/29584087/9410bfb4-d957-4f01-ba45-3c809a78e19c">

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

## Anything else we need to know?

Low priority

**Comment by kazo0** [comment]
Yes we should remove this shadow, was added for screenshot/documentation purposes

**Comment by agneszitte** [comment]
re-open for backport
