### ISSUE TITLE
[Shadow Builder][Safari] Clicking the IconToggleButtons randomly scrolls the page back to the top

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Gallery#985]
## Current behavior

https://github.com/unoplatform/Uno.Gallery/assets/29584087/ea56791c-ce73-40c4-ac01-d9e025437fcb

Clicking the ToggleButtons will at times trigger a scroll-to-top and it seems to happen randomly, clicking the same button twice will not always give you the same result.

## Expected behavior

No scrolling at all

## How to reproduce it (as minimally and precisely as possible)

Launch latest safari on mac and navigate to shadowcontainer/IconToggleButton

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] MacOs
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

May be related to an issue @eriklimakc is investigating about this behaviour in Chrome in one of his branches

**Comment by eriklimakc** [comment]
I have the same behavior in[ one of my branches ](https://github.com/unoplatform/uno.chefs/pull/568)for Chefs, but not only on Safari, but also in Chrome, and on Android as well.

![image-android-issue-toggle-button](https://github.com/unoplatform/uno.chefs/assets/114886335/4e938faf-dfd4-4b3a-a947-c905a7ac1dc8)

**Comment by ajpinedam** [comment]
@eriklimakc, can I have access to that branch?

Issues seem similar, but starting from the fact that it looks like a ListView/ItemsControl in your sample, I want to say they are different. 

I will check it out too.

**Comment by eriklimakc** [comment]
Also happens (tested Chrome) on this PR https://github.com/unoplatform/Uno.Themes/pull/997.

You can see in the static wasm link here: https://salmon-rock-0cfebe70f-997.eastus2.azurestaticapps.net/

Go to Helpers > ControlExtensions > Click the Leading or Trailing Icon in the TextBox example.

**Comment by jeromelaban** [comment]
I'm not able to reproduce with latest builds of Safari, @ajpinedam could you validate again? Thanks!

**Comment by ajpinedam** [comment]
> I'm not able to reproduce with latest builds of Safari, @ajpinedam could you validate again? Thanks!

It was reported a similar issue in Chefs and other apps, so the issue still seems to be there.

**Comment by Xiaoy312** [comment]
i just noticed something perhaps similar on-focus-lost: 
- open https://unogallerycanary.z27.web.core.windows.net/
- go to Toolkit\ShadowContainer, 
- scroll down all the way down
- choose `ToggleButton` from the combo-box
- (now click anywhere empty (that doesnt respond to click))
  > notice that the page doesnt move
- if you click on any of the toggle buttons, and then repeat the previous step
  > the page will scroll up somehow

i am using Chrome (Version 120.0.6099.217 (Official Build) (64-bit))
![gallery shadow toggle onfocuslost](https://github.com/unoplatform/Uno.Gallery/assets/2359550/b70b7dce-5c28-4a06-8a40-1db5b2ed2811)

**Comment by ramezgerges** [comment]
Following Xiao's repro steps gave a different repro. Tested on vivaldi, brave and firefox.

- open https://unogallerycanary.z27.web.core.windows.net/
- scroll all the way down
- now click anywhere empty
  > the page will scroll up somehow

This will only work when a page is first loaded. Changing the page makes it repro again. Also, changing the control in the checkbox inside Toolkit\ShadowContainer will also make it repro (any control will do, not necessarily ToggleButton).

**Comment by jeromelaban** [comment]
I cannot reproduce this issue anymore in the canary. @sakshi173 can you try again?

**Comment by NVLudwig** [comment]
@jeromelaban I reproed it just now check out the recording here.
https://github.com/unoplatform/Uno.Gallery/assets/29584087/64615120-bd98-45c2-becb-358b11580869

Note that the expanders in the gallery main navigation do the same thing bu on every click: opening a sections scrolls the list all the way back to the top:

https://github.com/unoplatform/Uno.Gallery/assets/29584087/2d940c0f-d026-4a84-b069-8b61ea2c6f55

I get both issues on both Safari and Chrome

**Comment by jeromelaban** [comment]
@NVLudwig this happens in prod, but not on the canary. Can you validate: https://unogallerycanary.z27.web.core.windows.net

**Comment by jeromelaban** [comment]
@sakshi173 can test on your mac now please?

**Comment by sakshi173** [comment]
@Jerome, I retested this defect on Mac book, and I am able to reproduce it. below is the video

https://github.com/unoplatform/Uno.Gallery/assets/74563602/74b50563-caca-4c67-9d22-587274c662a8

**Comment by jeromelaban** [comment]
@sakshi173 I'm sorry, I do not see what you're reproducing. I don't see any scrolling up? What are you reproducing?

**Comment by NVLudwig** [comment]
I think the video refers to one of the other 2 issues I found and was asking about [higher up](https://github.com/unoplatform/Uno.Gallery/issues/985#issuecomment-2135321725) in this thread

**Comment by jeromelaban** [comment]
Thanks. I see, let's not deal with multiple issues in a single issue. Let's split them instead.

**Comment by jeromelaban** [comment]
This issue is now split to https://github.com/unoplatform/Uno.Themes/issues/1430 and https://github.com/unoplatform/Uno.Themes/issues/1431
