### ISSUE TITLE
Material Sliders are swapped

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#988]
## Current behavior

The slider samples are swapped. Horizontal sample should go first.

![image](https://github.com/unoplatform/Uno.Gallery/assets/1075116/d9194844-c432-43ba-a395-b3f841a83c9c)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment]
Fixed by https://github.com/unoplatform/Uno.Gallery/pull/1000
